name: cgamp_env
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch==1.10.1
  - torchvision==0.11.2
  - torchaudio==0.10.1
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - numpy
  - scikit-learn
  - pandas
  - tqdm
  - pip:
      - torch-geometric==2.0.3
      - torch-scatter==2.0.9
      - torch-sparse==0.6.12
      - torch-cluster==1.5.9
      - torch-spline-conv==1.2.1
      - ogb==1.3.4
      - fair-esm
      - biopython
      - matplotlib
      - seaborn
      - networkx
      - scikit-optimize
